/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables;


import java.util.Collection;

import org.acumen.training.codes.model.Keys;
import org.acumen.training.codes.model.Public;
import org.acumen.training.codes.model.tables.records.InsuranceRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Insurance extends TableImpl<InsuranceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.insurance</code>
     */
    public static final Insurance INSURANCE = new Insurance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InsuranceRecord> getRecordType() {
        return InsuranceRecord.class;
    }

    /**
     * The column <code>public.insurance.policyid</code>.
     */
    public final TableField<InsuranceRecord, Integer> POLICYID = createField(DSL.name("policyid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.insurance.id</code>.
     */
    public final TableField<InsuranceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    private Insurance(Name alias, Table<InsuranceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Insurance(Name alias, Table<InsuranceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.insurance</code> table reference
     */
    public Insurance(String alias) {
        this(DSL.name(alias), INSURANCE);
    }

    /**
     * Create an aliased <code>public.insurance</code> table reference
     */
    public Insurance(Name alias) {
        this(alias, INSURANCE);
    }

    /**
     * Create a <code>public.insurance</code> table reference
     */
    public Insurance() {
        this(DSL.name("insurance"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InsuranceRecord, Integer> getIdentity() {
        return (Identity<InsuranceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InsuranceRecord> getPrimaryKey() {
        return Keys.INSURANCE_PKEY;
    }

    @Override
    public Insurance as(String alias) {
        return new Insurance(DSL.name(alias), this);
    }

    @Override
    public Insurance as(Name alias) {
        return new Insurance(alias, this);
    }

    @Override
    public Insurance as(Table<?> alias) {
        return new Insurance(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Insurance rename(String name) {
        return new Insurance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Insurance rename(Name name) {
        return new Insurance(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Insurance rename(Table<?> name) {
        return new Insurance(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Insurance where(Condition condition) {
        return new Insurance(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Insurance where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Insurance where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Insurance where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Insurance where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Insurance where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Insurance where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Insurance where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Insurance whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Insurance whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
