/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables;


import java.util.Collection;

import org.acumen.training.codes.model.Keys;
import org.acumen.training.codes.model.Public;
import org.acumen.training.codes.model.tables.records.UtilityRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Utility extends TableImpl<UtilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.utility</code>
     */
    public static final Utility UTILITY = new Utility();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtilityRecord> getRecordType() {
        return UtilityRecord.class;
    }

    /**
     * The column <code>public.utility.id</code>.
     */
    public final TableField<UtilityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.utility.fullname</code>.
     */
    public final TableField<UtilityRecord, String> FULLNAME = createField(DSL.name("fullname"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private Utility(Name alias, Table<UtilityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Utility(Name alias, Table<UtilityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.utility</code> table reference
     */
    public Utility(String alias) {
        this(DSL.name(alias), UTILITY);
    }

    /**
     * Create an aliased <code>public.utility</code> table reference
     */
    public Utility(Name alias) {
        this(alias, UTILITY);
    }

    /**
     * Create a <code>public.utility</code> table reference
     */
    public Utility() {
        this(DSL.name("utility"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UtilityRecord, Integer> getIdentity() {
        return (Identity<UtilityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UtilityRecord> getPrimaryKey() {
        return Keys.UTILITY_PKEY;
    }

    @Override
    public Utility as(String alias) {
        return new Utility(DSL.name(alias), this);
    }

    @Override
    public Utility as(Name alias) {
        return new Utility(alias, this);
    }

    @Override
    public Utility as(Table<?> alias) {
        return new Utility(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Utility rename(String name) {
        return new Utility(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utility rename(Name name) {
        return new Utility(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utility rename(Table<?> name) {
        return new Utility(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utility where(Condition condition) {
        return new Utility(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utility where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utility where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utility where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utility where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utility where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utility where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utility where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utility whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utility whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
