package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Allowance generated by hbm2java
 */
@Entity
@Table(name = "allowance", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class Allowance implements java.io.Serializable {

	private int allowanceid;
	private int id;

	public Allowance() {
	}

	public Allowance(int allowanceid, int id) {
		this.allowanceid = allowanceid;
		this.id = id;
	}

	@Id

	@Column(name = "allowanceid", unique = true, nullable = false)
	public int getAllowanceid() {
		return this.allowanceid;
	}

	public void setAllowanceid(int allowanceid) {
		this.allowanceid = allowanceid;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
