package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DataTypesId generated by hbm2java
 */
@Embeddable
public class DataTypesId implements java.io.Serializable {

	private short age;
	private int empid;
	private long popsize;
	private double salary;
	private Float accountAmount;
	private byte donation;
	private BigDecimal mortage;
	private String nickname;
	private String position;
	private String comment;
	private boolean isemployed;
	private Date timein;
	private Date birthday;
	private Date dateresigned;
	private Date moneytxdate;
	private int id;
	private double amount;
	private boolean isturnoff;
	private byte[] picture;

	public DataTypesId() {
	}

	public DataTypesId(short age, int empid, long popsize, double salary, byte donation, BigDecimal mortage,
			String nickname, String position, String comment, boolean isemployed, Date timein, Date birthday,
			Date dateresigned, Date moneytxdate, int id, double amount, boolean isturnoff, byte[] picture) {
		this.age = age;
		this.empid = empid;
		this.popsize = popsize;
		this.salary = salary;
		this.donation = donation;
		this.mortage = mortage;
		this.nickname = nickname;
		this.position = position;
		this.comment = comment;
		this.isemployed = isemployed;
		this.timein = timein;
		this.birthday = birthday;
		this.dateresigned = dateresigned;
		this.moneytxdate = moneytxdate;
		this.id = id;
		this.amount = amount;
		this.isturnoff = isturnoff;
		this.picture = picture;
	}

	public DataTypesId(short age, int empid, long popsize, double salary, Float accountAmount, byte donation,
			BigDecimal mortage, String nickname, String position, String comment, boolean isemployed, Date timein,
			Date birthday, Date dateresigned, Date moneytxdate, int id, double amount, boolean isturnoff,
			byte[] picture) {
		this.age = age;
		this.empid = empid;
		this.popsize = popsize;
		this.salary = salary;
		this.accountAmount = accountAmount;
		this.donation = donation;
		this.mortage = mortage;
		this.nickname = nickname;
		this.position = position;
		this.comment = comment;
		this.isemployed = isemployed;
		this.timein = timein;
		this.birthday = birthday;
		this.dateresigned = dateresigned;
		this.moneytxdate = moneytxdate;
		this.id = id;
		this.amount = amount;
		this.isturnoff = isturnoff;
		this.picture = picture;
	}

	@Column(name = "age", nullable = false)
	public short getAge() {
		return this.age;
	}

	public void setAge(short age) {
		this.age = age;
	}

	@Column(name = "empid", unique = true, nullable = false)
	public int getEmpid() {
		return this.empid;
	}

	public void setEmpid(int empid) {
		this.empid = empid;
	}

	@Column(name = "popsize", nullable = false)
	public long getPopsize() {
		return this.popsize;
	}

	public void setPopsize(long popsize) {
		this.popsize = popsize;
	}

	@Column(name = "salary", nullable = false, precision = 17, scale = 17)
	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	@Column(name = "account_amount", precision = 8, scale = 8)
	public Float getAccountAmount() {
		return this.accountAmount;
	}

	public void setAccountAmount(Float accountAmount) {
		this.accountAmount = accountAmount;
	}

	@Column(name = "donation", nullable = false, precision = 0, scale = 0)
	public byte getDonation() {
		return this.donation;
	}

	public void setDonation(byte donation) {
		this.donation = donation;
	}

	@Column(name = "mortage", nullable = false, precision = 10, scale = 3)
	public BigDecimal getMortage() {
		return this.mortage;
	}

	public void setMortage(BigDecimal mortage) {
		this.mortage = mortage;
	}

	@Column(name = "nickname", nullable = false, length = 10)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "position", nullable = false, length = 200)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "comment", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "isemployed", nullable = false)
	public boolean isIsemployed() {
		return this.isemployed;
	}

	public void setIsemployed(boolean isemployed) {
		this.isemployed = isemployed;
	}

	@Column(name = "timein", nullable = false, length = 15)
	public Date getTimein() {
		return this.timein;
	}

	public void setTimein(Date timein) {
		this.timein = timein;
	}

	@Column(name = "birthday", nullable = false, length = 13)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "dateresigned", nullable = false, length = 29)
	public Date getDateresigned() {
		return this.dateresigned;
	}

	public void setDateresigned(Date dateresigned) {
		this.dateresigned = dateresigned;
	}

	@Column(name = "moneytxdate", nullable = false, length = 35)
	public Date getMoneytxdate() {
		return this.moneytxdate;
	}

	public void setMoneytxdate(Date moneytxdate) {
		this.moneytxdate = moneytxdate;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "isturnoff", nullable = false)
	public boolean isIsturnoff() {
		return this.isturnoff;
	}

	public void setIsturnoff(boolean isturnoff) {
		this.isturnoff = isturnoff;
	}

	@Column(name = "picture", nullable = false)
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataTypesId))
			return false;
		DataTypesId castOther = (DataTypesId) other;

		return (this.getAge() == castOther.getAge()) && (this.getEmpid() == castOther.getEmpid())
				&& (this.getPopsize() == castOther.getPopsize()) && (this.getSalary() == castOther.getSalary())
				&& ((this.getAccountAmount() == castOther.getAccountAmount())
						|| (this.getAccountAmount() != null && castOther.getAccountAmount() != null
								&& this.getAccountAmount().equals(castOther.getAccountAmount())))
				&& (this.getDonation() == castOther.getDonation())
				&& ((this.getMortage() == castOther.getMortage()) || (this.getMortage() != null
						&& castOther.getMortage() != null && this.getMortage().equals(castOther.getMortage())))
				&& ((this.getNickname() == castOther.getNickname()) || (this.getNickname() != null
						&& castOther.getNickname() != null && this.getNickname().equals(castOther.getNickname())))
				&& ((this.getPosition() == castOther.getPosition()) || (this.getPosition() != null
						&& castOther.getPosition() != null && this.getPosition().equals(castOther.getPosition())))
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())))
				&& (this.isIsemployed() == castOther.isIsemployed())
				&& ((this.getTimein() == castOther.getTimein()) || (this.getTimein() != null
						&& castOther.getTimein() != null && this.getTimein().equals(castOther.getTimein())))
				&& ((this.getBirthday() == castOther.getBirthday()) || (this.getBirthday() != null
						&& castOther.getBirthday() != null && this.getBirthday().equals(castOther.getBirthday())))
				&& ((this.getDateresigned() == castOther.getDateresigned())
						|| (this.getDateresigned() != null && castOther.getDateresigned() != null
								&& this.getDateresigned().equals(castOther.getDateresigned())))
				&& ((this.getMoneytxdate() == castOther.getMoneytxdate())
						|| (this.getMoneytxdate() != null && castOther.getMoneytxdate() != null
								&& this.getMoneytxdate().equals(castOther.getMoneytxdate())))
				&& (this.getId() == castOther.getId()) && (this.getAmount() == castOther.getAmount())
				&& (this.isIsturnoff() == castOther.isIsturnoff())
				&& ((this.getPicture() == castOther.getPicture()) || (this.getPicture() != null
						&& castOther.getPicture() != null && Arrays.equals(this.getPicture(), castOther.getPicture())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAge();
		result = 37 * result + this.getEmpid();
		result = 37 * result + (int) this.getPopsize();
		result = 37 * result + (int) this.getSalary();
		result = 37 * result + (getAccountAmount() == null ? 0 : this.getAccountAmount().hashCode());
		result = 37 * result + this.getDonation();
		result = 37 * result + (getMortage() == null ? 0 : this.getMortage().hashCode());
		result = 37 * result + (getNickname() == null ? 0 : this.getNickname().hashCode());
		result = 37 * result + (getPosition() == null ? 0 : this.getPosition().hashCode());
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result + (this.isIsemployed() ? 1 : 0);
		result = 37 * result + (getTimein() == null ? 0 : this.getTimein().hashCode());
		result = 37 * result + (getBirthday() == null ? 0 : this.getBirthday().hashCode());
		result = 37 * result + (getDateresigned() == null ? 0 : this.getDateresigned().hashCode());
		result = 37 * result + (getMoneytxdate() == null ? 0 : this.getMoneytxdate().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (int) this.getAmount();
		result = 37 * result + (this.isIsturnoff() ? 1 : 0);
		int pictureHashcode = 0;
		byte[] pictureProperty = this.getPicture();
		if (pictureProperty != null) {
			pictureHashcode = 1;
			for (int i = 0; i < pictureProperty.length; i++) {
				pictureHashcode = 37 * pictureHashcode + pictureProperty[i];
			}
		}

		result = 37 * result + pictureHashcode;

		return result;
	}

}
