package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DataTypes generated by hbm2java
 */
@Entity
@Table(name = "data_types", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "empid"))
public class DataTypes implements java.io.Serializable {

	private DataTypesId id;

	public DataTypes() {
	}

	public DataTypes(DataTypesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "age", column = @Column(name = "age", nullable = false)),
			@AttributeOverride(name = "empid", column = @Column(name = "empid", unique = true, nullable = false)),
			@AttributeOverride(name = "popsize", column = @Column(name = "popsize", nullable = false)),
			@AttributeOverride(name = "salary", column = @Column(name = "salary", nullable = false, precision = 17, scale = 17)),
			@AttributeOverride(name = "accountAmount", column = @Column(name = "account_amount", precision = 8, scale = 8)),
			@AttributeOverride(name = "donation", column = @Column(name = "donation", nullable = false, precision = 0, scale = 0)),
			@AttributeOverride(name = "mortage", column = @Column(name = "mortage", nullable = false, precision = 10, scale = 3)),
			@AttributeOverride(name = "nickname", column = @Column(name = "nickname", nullable = false, length = 10)),
			@AttributeOverride(name = "position", column = @Column(name = "position", nullable = false, length = 200)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", nullable = false)),
			@AttributeOverride(name = "isemployed", column = @Column(name = "isemployed", nullable = false)),
			@AttributeOverride(name = "timein", column = @Column(name = "timein", nullable = false, length = 15)),
			@AttributeOverride(name = "birthday", column = @Column(name = "birthday", nullable = false, length = 13)),
			@AttributeOverride(name = "dateresigned", column = @Column(name = "dateresigned", nullable = false, length = 29)),
			@AttributeOverride(name = "moneytxdate", column = @Column(name = "moneytxdate", nullable = false, length = 35)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, scale = 0)),
			@AttributeOverride(name = "isturnoff", column = @Column(name = "isturnoff", nullable = false)),
			@AttributeOverride(name = "picture", column = @Column(name = "picture", nullable = false)) })
	public DataTypesId getId() {
		return this.id;
	}

	public void setId(DataTypesId id) {
		this.id = id;
	}

}
