package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectDataViewId generated by hbm2java
 */
@Embeddable
public class ProjectDataViewId implements java.io.Serializable {

	private Integer projid;
	private String projname;
	private Date projdate;
	private Integer id;
	private String firstname;
	private String lastname;

	public ProjectDataViewId() {
	}

	public ProjectDataViewId(Integer projid, String projname, Date projdate, Integer id, String firstname,
			String lastname) {
		this.projid = projid;
		this.projname = projname;
		this.projdate = projdate;
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
	}

	@Column(name = "projid")
	public Integer getProjid() {
		return this.projid;
	}

	public void setProjid(Integer projid) {
		this.projid = projid;
	}

	@Column(name = "projname", length = 200)
	public String getProjname() {
		return this.projname;
	}

	public void setProjname(String projname) {
		this.projname = projname;
	}

	@Column(name = "projdate", length = 13)
	public Date getProjdate() {
		return this.projdate;
	}

	public void setProjdate(Date projdate) {
		this.projdate = projdate;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", length = 60)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 60)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectDataViewId))
			return false;
		ProjectDataViewId castOther = (ProjectDataViewId) other;

		return ((this.getProjid() == castOther.getProjid()) || (this.getProjid() != null
				&& castOther.getProjid() != null && this.getProjid().equals(castOther.getProjid())))
				&& ((this.getProjname() == castOther.getProjname()) || (this.getProjname() != null
						&& castOther.getProjname() != null && this.getProjname().equals(castOther.getProjname())))
				&& ((this.getProjdate() == castOther.getProjdate()) || (this.getProjdate() != null
						&& castOther.getProjdate() != null && this.getProjdate().equals(castOther.getProjdate())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getFirstname() == castOther.getFirstname()) || (this.getFirstname() != null
						&& castOther.getFirstname() != null && this.getFirstname().equals(castOther.getFirstname())))
				&& ((this.getLastname() == castOther.getLastname()) || (this.getLastname() != null
						&& castOther.getLastname() != null && this.getLastname().equals(castOther.getLastname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjid() == null ? 0 : this.getProjid().hashCode());
		result = 37 * result + (getProjname() == null ? 0 : this.getProjname().hashCode());
		result = 37 * result + (getProjdate() == null ? 0 : this.getProjdate().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		result = 37 * result + (getLastname() == null ? 0 : this.getLastname().hashCode());
		return result;
	}

}
