package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", schema = "public")
public class Project implements java.io.Serializable {

	private short projid;
	private String projname;
	private Date projdate;
	private Set projectMemberses = new HashSet(0);

	public Project() {
	}

	public Project(short projid, String projname, Date projdate) {
		this.projid = projid;
		this.projname = projname;
		this.projdate = projdate;
	}

	public Project(short projid, String projname, Date projdate, Set projectMemberses) {
		this.projid = projid;
		this.projname = projname;
		this.projdate = projdate;
		this.projectMemberses = projectMemberses;
	}

	@Id

	@Column(name = "projid", unique = true, nullable = false)
	public short getProjid() {
		return this.projid;
	}

	public void setProjid(short projid) {
		this.projid = projid;
	}

	@Column(name = "projname", nullable = false, length = 200)
	public String getProjname() {
		return this.projname;
	}

	public void setProjname(String projname) {
		this.projname = projname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "projdate", nullable = false, length = 13)
	public Date getProjdate() {
		return this.projdate;
	}

	public void setProjdate(Date projdate) {
		this.projdate = projdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getProjectMemberses() {
		return this.projectMemberses;
	}

	public void setProjectMemberses(Set projectMemberses) {
		this.projectMemberses = projectMemberses;
	}

}
