package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectDataView generated by hbm2java
 */
@Entity
@Table(name = "project_data_view", schema = "public")
public class ProjectDataView implements java.io.Serializable {

	private ProjectDataViewId id;

	public ProjectDataView() {
	}

	public ProjectDataView(ProjectDataViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projid", column = @Column(name = "projid")),
			@AttributeOverride(name = "projname", column = @Column(name = "projname", length = 200)),
			@AttributeOverride(name = "projdate", column = @Column(name = "projdate", length = 13)),
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "firstname", column = @Column(name = "firstname", length = 60)),
			@AttributeOverride(name = "lastname", column = @Column(name = "lastname", length = 60)) })
	public ProjectDataViewId getId() {
		return this.id;
	}

	public void setId(ProjectDataViewId id) {
		this.id = id;
	}

}
