package org.acumen.training.codes.model;
// Generated 24 Oct 2024, 1:17:56 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stocks generated by hbm2java
 */
@Entity
@Table(name = "stocks", schema = "public")
public class Stocks implements java.io.Serializable {

	private short id;
	private Double commission;
	private Double rate;
	private double amount;

	public Stocks() {
	}

	public Stocks(short id, double amount) {
		this.id = id;
		this.amount = amount;
	}

	public Stocks(short id, Double commission, Double rate, double amount) {
		this.id = id;
		this.commission = commission;
		this.rate = rate;
		this.amount = amount;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "commission", precision = 17, scale = 17)
	public Double getCommission() {
		return this.commission;
	}

	public void setCommission(Double commission) {
		this.commission = commission;
	}

	@Column(name = "rate", precision = 17, scale = 17)
	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Column(name = "amount", nullable = false, precision = 17, scale = 17)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

}
