/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables.records;


import org.acumen.training.codes.model.tables.Administrator;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdministratorRecord extends UpdatableRecordImpl<AdministratorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.administrator.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.administrator.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.administrator.fullname</code>.
     */
    public void setFullname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.administrator.fullname</code>.
     */
    public String getFullname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.administrator.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.administrator.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdministratorRecord
     */
    public AdministratorRecord() {
        super(Administrator.ADMINISTRATOR);
    }

    /**
     * Create a detached, initialised AdministratorRecord
     */
    public AdministratorRecord(Integer id, String fullname, String role) {
        super(Administrator.ADMINISTRATOR);

        setId(id);
        setFullname(fullname);
        setRole(role);
        resetChangedOnNotNull();
    }
}
