/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables.records;


import org.acumen.training.codes.model.tables.Insurance;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InsuranceRecord extends UpdatableRecordImpl<InsuranceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.insurance.policyid</code>.
     */
    public void setPolicyid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.insurance.policyid</code>.
     */
    public Integer getPolicyid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.insurance.id</code>.
     */
    public void setId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.insurance.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InsuranceRecord
     */
    public InsuranceRecord() {
        super(Insurance.INSURANCE);
    }

    /**
     * Create a detached, initialised InsuranceRecord
     */
    public InsuranceRecord(Integer policyid, Integer id) {
        super(Insurance.INSURANCE);

        setPolicyid(policyid);
        setId(id);
        resetChangedOnNotNull();
    }
}
