/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables.records;


import java.time.LocalDate;

import org.acumen.training.codes.model.tables.Manager;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ManagerRecord extends UpdatableRecordImpl<ManagerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.manager.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.manager.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.manager.firstname</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.manager.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.manager.gender</code>.
     */
    public void setGender(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.manager.gender</code>.
     */
    public String getGender() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.manager.age</code>.
     */
    public void setAge(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.manager.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.manager.salary</code>.
     */
    public void setSalary(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.manager.salary</code>.
     */
    public Double getSalary() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.manager.birthday</code>.
     */
    public void setBirthday(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.manager.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.manager.supervisor</code>.
     */
    public void setSupervisor(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.manager.supervisor</code>.
     */
    public Integer getSupervisor() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManagerRecord
     */
    public ManagerRecord() {
        super(Manager.MANAGER);
    }

    /**
     * Create a detached, initialised ManagerRecord
     */
    public ManagerRecord(Integer id, String firstname, String gender, Integer age, Double salary, LocalDate birthday, Integer supervisor) {
        super(Manager.MANAGER);

        setId(id);
        setFirstname(firstname);
        setGender(gender);
        setAge(age);
        setSalary(salary);
        setBirthday(birthday);
        setSupervisor(supervisor);
        resetChangedOnNotNull();
    }
}
