/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables.records;


import org.acumen.training.codes.model.tables.ProjectMembers;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectMembersRecord extends UpdatableRecordImpl<ProjectMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project_members.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project_members.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.project_members.firstname</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project_members.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.project_members.lastname</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project_members.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.project_members.projid</code>.
     */
    public void setProjid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.project_members.projid</code>.
     */
    public Integer getProjid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectMembersRecord
     */
    public ProjectMembersRecord() {
        super(ProjectMembers.PROJECT_MEMBERS);
    }

    /**
     * Create a detached, initialised ProjectMembersRecord
     */
    public ProjectMembersRecord(Integer id, String firstname, String lastname, Integer projid) {
        super(ProjectMembers.PROJECT_MEMBERS);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setProjid(projid);
        resetChangedOnNotNull();
    }
}
