/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.tables.records;


import java.time.LocalDate;

import org.acumen.training.codes.model.tables.Project;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project.projid</code>.
     */
    public void setProjid(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project.projid</code>.
     */
    public Short getProjid() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.project.projname</code>.
     */
    public void setProjname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project.projname</code>.
     */
    public String getProjname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.project.projdate</code>.
     */
    public void setProjdate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project.projdate</code>.
     */
    public LocalDate getProjdate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(Short projid, String projname, LocalDate projdate) {
        super(Project.PROJECT);

        setProjid(projid);
        setProjname(projname);
        setProjdate(projdate);
        resetChangedOnNotNull();
    }
}
