/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.routines;


import org.acumen.training.codes.model.Public;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IncreaseSalarySp extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.increase_salary_sp.inc_salary</code>.
     */
    public static final Parameter<Double> INC_SALARY = Internal.createParameter("inc_salary", SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>public.increase_salary_sp.idlcl</code>.
     */
    public static final Parameter<Integer> IDLCL = Internal.createParameter("idlcl", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.increase_salary_sp.is_success</code>.
     */
    public static final Parameter<Boolean> IS_SUCCESS = Internal.createParameter("is_success", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public IncreaseSalarySp() {
        super("increase_salary_sp", Public.PUBLIC);

        addInParameter(INC_SALARY);
        addInParameter(IDLCL);
        addInOutParameter(IS_SUCCESS);
        setSQLUsable(false);
    }

    /**
     * Set the <code>inc_salary</code> parameter IN value to the routine
     */
    public void setIncSalary(Double value) {
        setValue(INC_SALARY, value);
    }

    /**
     * Set the <code>idlcl</code> parameter IN value to the routine
     */
    public void setIdlcl(Integer value) {
        setValue(IDLCL, value);
    }

    /**
     * Set the <code>is_success</code> parameter IN value to the routine
     */
    public void setIsSuccess(Boolean value) {
        setValue(IS_SUCCESS, value);
    }

    /**
     * Get the <code>is_success</code> parameter OUT value from the routine
     */
    public Boolean getIsSuccess() {
        return get(IS_SUCCESS);
    }
}
