/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.routines;


import java.time.LocalDate;

import org.acumen.training.codes.model.Public;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InsertProjectCountSp1 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.insert_project_count_sp.id</code>.
     */
    public static final Parameter<Integer> ID = Internal.createParameter("id", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.insert_project_count_sp.pname</code>.
     */
    public static final Parameter<String> PNAME = Internal.createParameter("pname", SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>public.insert_project_count_sp.pdate</code>.
     */
    public static final Parameter<LocalDate> PDATE = Internal.createParameter("pdate", SQLDataType.LOCALDATE, false, false);

    /**
     * Create a new routine call instance
     */
    public InsertProjectCountSp1() {
        super("insert_project_count_sp", Public.PUBLIC);

        addInParameter(ID);
        addInParameter(PNAME);
        addInParameter(PDATE);
        setOverloaded(true);
        setSQLUsable(false);
    }

    /**
     * Set the <code>id</code> parameter IN value to the routine
     */
    public void setId(Integer value) {
        setValue(ID, value);
    }

    /**
     * Set the <code>pname</code> parameter IN value to the routine
     */
    public void setPname(String value) {
        setValue(PNAME, value);
    }

    /**
     * Set the <code>pdate</code> parameter IN value to the routine
     */
    public void setPdate(LocalDate value) {
        setValue(PDATE, value);
    }
}
