/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model.routines;


import org.acumen.training.codes.model.Public;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShowProjectsJoinCountSp extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public ShowProjectsJoinCountSp() {
        super("show_projects_join_count_sp", Public.PUBLIC);
        setSQLUsable(false);
    }
}
