/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model;


import java.util.Arrays;
import java.util.List;

import org.acumen.training.codes.model.tables.Administrator;
import org.acumen.training.codes.model.tables.Allowance;
import org.acumen.training.codes.model.tables.DataTypes;
import org.acumen.training.codes.model.tables.Developer;
import org.acumen.training.codes.model.tables.Insurance;
import org.acumen.training.codes.model.tables.Manager;
import org.acumen.training.codes.model.tables.Project;
import org.acumen.training.codes.model.tables.ProjectDataView;
import org.acumen.training.codes.model.tables.ProjectMembers;
import org.acumen.training.codes.model.tables.Stocks;
import org.acumen.training.codes.model.tables.Utility;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.administrator</code>.
     */
    public final Administrator ADMINISTRATOR = Administrator.ADMINISTRATOR;

    /**
     * The table <code>public.allowance</code>.
     */
    public final Allowance ALLOWANCE = Allowance.ALLOWANCE;

    /**
     * The table <code>public.data_types</code>.
     */
    public final DataTypes DATA_TYPES = DataTypes.DATA_TYPES;

    /**
     * The table <code>public.developer</code>.
     */
    public final Developer DEVELOPER = Developer.DEVELOPER;

    /**
     * The table <code>public.insurance</code>.
     */
    public final Insurance INSURANCE = Insurance.INSURANCE;

    /**
     * The table <code>public.manager</code>.
     */
    public final Manager MANAGER = Manager.MANAGER;

    /**
     * The table <code>public.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.project_data_view</code>.
     */
    public final ProjectDataView PROJECT_DATA_VIEW = ProjectDataView.PROJECT_DATA_VIEW;

    /**
     * The table <code>public.project_members</code>.
     */
    public final ProjectMembers PROJECT_MEMBERS = ProjectMembers.PROJECT_MEMBERS;

    /**
     * The table <code>public.stocks</code>.
     */
    public final Stocks STOCKS = Stocks.STOCKS;

    /**
     * The table <code>public.utility</code>.
     */
    public final Utility UTILITY = Utility.UTILITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Administrator.ADMINISTRATOR,
            Allowance.ALLOWANCE,
            DataTypes.DATA_TYPES,
            Developer.DEVELOPER,
            Insurance.INSURANCE,
            Manager.MANAGER,
            Project.PROJECT,
            ProjectDataView.PROJECT_DATA_VIEW,
            ProjectMembers.PROJECT_MEMBERS,
            Stocks.STOCKS,
            Utility.UTILITY
        );
    }
}
