/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model;


import java.time.LocalDate;

import org.acumen.training.codes.model.routines.Helloworld;
import org.acumen.training.codes.model.routines.IncreaseSalarySp;
import org.acumen.training.codes.model.routines.InsertProjectCountSp1;
import org.acumen.training.codes.model.routines.InsertProjectCountSp2;
import org.acumen.training.codes.model.routines.ShowProjectsJoinCountSp;
import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.helloworld</code>
     */
    public static void helloworld(
          Configuration configuration
    ) {
        Helloworld p = new Helloworld();

        p.execute(configuration);
    }

    /**
     * Call <code>public.increase_salary_sp</code>
     */
    public static Boolean increaseSalarySp(
          Configuration configuration
        , Double incSalary
        , Integer idlcl
        , Boolean isSuccess
    ) {
        IncreaseSalarySp p = new IncreaseSalarySp();
        p.setIncSalary(incSalary);
        p.setIdlcl(idlcl);
        p.setIsSuccess(isSuccess);

        p.execute(configuration);
        return p.getIsSuccess();
    }

    /**
     * Call <code>public.insert_project_count_sp</code>
     */
    public static void insertProjectCountSp1(
          Configuration configuration
        , Integer id
        , String pname
        , LocalDate pdate
    ) {
        InsertProjectCountSp1 p = new InsertProjectCountSp1();
        p.setId(id);
        p.setPname(pname);
        p.setPdate(pdate);

        p.execute(configuration);
    }

    /**
     * Call <code>public.insert_project_count_sp</code>
     */
    public static Integer insertProjectCountSp2(
          Configuration configuration
        , Integer id
        , String pname
        , LocalDate pdate
        , Integer rcount
    ) {
        InsertProjectCountSp2 p = new InsertProjectCountSp2();
        p.setId(id);
        p.setPname(pname);
        p.setPdate(pdate);
        p.setRcount(rcount);

        p.execute(configuration);
        return p.getRcount();
    }

    /**
     * Call <code>public.show_projects_join_count_sp</code>
     */
    public static void showProjectsJoinCountSp(
          Configuration configuration
    ) {
        ShowProjectsJoinCountSp p = new ShowProjectsJoinCountSp();

        p.execute(configuration);
    }
}
