/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model;


import org.acumen.training.codes.model.tables.Administrator;
import org.acumen.training.codes.model.tables.Allowance;
import org.acumen.training.codes.model.tables.DataTypes;
import org.acumen.training.codes.model.tables.Developer;
import org.acumen.training.codes.model.tables.Insurance;
import org.acumen.training.codes.model.tables.Manager;
import org.acumen.training.codes.model.tables.Project;
import org.acumen.training.codes.model.tables.ProjectDataView;
import org.acumen.training.codes.model.tables.ProjectMembers;
import org.acumen.training.codes.model.tables.Stocks;
import org.acumen.training.codes.model.tables.Utility;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.administrator</code>.
     */
    public static final Administrator ADMINISTRATOR = Administrator.ADMINISTRATOR;

    /**
     * The table <code>public.allowance</code>.
     */
    public static final Allowance ALLOWANCE = Allowance.ALLOWANCE;

    /**
     * The table <code>public.data_types</code>.
     */
    public static final DataTypes DATA_TYPES = DataTypes.DATA_TYPES;

    /**
     * The table <code>public.developer</code>.
     */
    public static final Developer DEVELOPER = Developer.DEVELOPER;

    /**
     * The table <code>public.insurance</code>.
     */
    public static final Insurance INSURANCE = Insurance.INSURANCE;

    /**
     * The table <code>public.manager</code>.
     */
    public static final Manager MANAGER = Manager.MANAGER;

    /**
     * The table <code>public.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.project_data_view</code>.
     */
    public static final ProjectDataView PROJECT_DATA_VIEW = ProjectDataView.PROJECT_DATA_VIEW;

    /**
     * The table <code>public.project_members</code>.
     */
    public static final ProjectMembers PROJECT_MEMBERS = ProjectMembers.PROJECT_MEMBERS;

    /**
     * The table <code>public.stocks</code>.
     */
    public static final Stocks STOCKS = Stocks.STOCKS;

    /**
     * The table <code>public.utility</code>.
     */
    public static final Utility UTILITY = Utility.UTILITY;
}
